services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    ports:
      - "0.0.0.0:8085:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro # Archivo de configuración principal
      - ./traefik/config:/etc/traefik/config:ro
    networks:
      - eam-elecitva-balancer

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - eam-elecitva-balancer
    labels:
      - "traefik.enable=false"

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    # Add explicit port mapping for direct access
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
      - ADMINER_DESIGN=flat
    networks:
      - eam-elecitva-balancer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=PathPrefix(`/adminer`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.http.routers.adminer.entrypoints=web"

  api:
    build:
      context: ./fastapi
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: '0.75'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mysql:3306/mydatabase
    networks:
      - eam-elecitva-balancer
    depends_on:
      - mysql
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
        - "traefik.http.services.api.loadbalancer.server.port=8000"
        - "traefik.http.routers.api.entrypoints=web"
        - "traefik.http.services.api.loadbalancer.sticky=true"
        - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"
        - "traefik.http.middlewares.api-strip.stripprefix.forceSlash=false"
        - "traefik.http.routers.api.middlewares=api-strip@docker"
        - "traefik.http.middlewares.api-headers.headers.customrequestheaders.X-Forwarded-Prefix=/api"

networks:
  eam-elecitva-balancer:
    driver: bridge

volumes:
  mysql_data: